/**
 * LINE protocol constants — operation types and content types.
 */

export const OP_TYPE = {
  END_OF_OPERATION: 0,
  UPDATE_PROFILE: 1,
  NOTIFIED_UPDATE_PROFILE: 2,
  RECEIVE_MESSAGE: 26,
  SEND_MESSAGE: 25,
  RECEIVE_MESSAGE_RECEIPT: 28,
  SEND_MESSAGE_RECEIPT: 29,
  NOTIFIED_READ_MESSAGE: 55,
  NOTIFIED_UNREAD_COUNT: 56,
  NOTIFIED_DESTROY_MESSAGE: 61,
  NOTIFIED_TYPING: 90,
  ADD_CONTACT: 15,
  BLOCK_CONTACT: 16,
  UNBLOCK_CONTACT: 17,
  UPDATE_GROUP: 9,
  NOTIFIED_UPDATE_GROUP: 10,
  INVITE_INTO_GROUP: 11,
  ACCEPT_GROUP_INVITATION: 13,
  LEAVE_GROUP: 31,
  NOTIFIED_INVITE_INTO_GROUP: 32,
  NOTIFIED_ACCEPT_GROUP_INVITATION: 34,
  NOTIFIED_LEAVE_GROUP: 35,
  KICKOUT_FROM_GROUP: 36,
};

export const CONTENT_TYPE = {
  NONE: 0,
  IMAGE: 1,
  VIDEO: 2,
  AUDIO: 3,
  HTML: 4,
  PDF: 5,
  CALL: 6,
  STICKER: 7,
  PRESENCE: 8,
  GIFT: 9,
  GROUPBOARD_NOTE: 10,
  GROUPBOARD_COMMENT: 11,
  LOCATION: 15,
  RICH_MESSAGE: 16,
  CONTACT: 18,
  FILE: 19,
  FLEX: 22,
};
