/**
 * LINE protocol constants — operation types and content types.
 */

export const OP_TYPE = {
  END_OF_OPERATION: 0,
  UPDATE_PROFILE: 1,
  NOTIFIED_UPDATE_PROFILE: 2,
  RECEIVE_MESSAGE: 26,
  SEND_MESSAGE: 25,
  RECEIVE_MESSAGE_RECEIPT: 28,
  SEND_MESSAGE_RECEIPT: 29,
  NOTIFIED_READ_MESSAGE: 55,
  NOTIFIED_UNREAD_COUNT: 56,
  NOTIFIED_DESTROY_MESSAGE: 61,
  NOTIFIED_TYPING: 90,
  ADD_CONTACT: 15,
  BLOCK_CONTACT: 16,
  UNBLOCK_CONTACT: 17,
  UPDATE_GROUP: 9,
  NOTIFIED_UPDATE_GROUP: 10,
  INVITE_INTO_GROUP: 11,
  ACCEPT_GROUP_INVITATION: 13,
  LEAVE_GROUP: 31,
  NOTIFIED_INVITE_INTO_GROUP: 32,
  NOTIFIED_ACCEPT_GROUP_INVITATION: 34,
  NOTIFIED_LEAVE_GROUP: 35,
  KICKOUT_FROM_GROUP: 36,
}

// Values mirror LINE's Thrift `ContentType` enum exactly. Do not renumber to
// match intuition: a wrong value silently misroutes a message type (e.g. FILE
// was 19 = MUSIC, so file attachments were never recognized as downloadable).
export const CONTENT_TYPE = {
  NONE: 0,
  IMAGE: 1,
  VIDEO: 2,
  AUDIO: 3,
  HTML: 4,
  PDF: 5,
  CALL: 6,
  STICKER: 7,
  PRESENCE: 8,
  GIFT: 9,
  GROUPBOARD: 10,
  APPLINK: 11,
  LINK: 12,
  CONTACT: 13,
  FILE: 14,
  LOCATION: 15,
  POSTNOTIFICATION: 16,
  RICH: 17,
  CHATEVENT: 18,
  MUSIC: 19,
  PAYMENT: 20,
  EXTIMAGE: 21,
  FLEX: 22,
}
